### ISSUE TITLE
ArraySource is not abstract and does not override abstract method getIndex() in DataSource

### ISSUE THREAD

**Issue by TehcJS** [Kneesnap/FrogLord#22]
Please help. I am going insane.
<img width="1154" alt="Screen Shot 2020-01-13 at 5 40 31 AM" src="https://user-images.githubusercontent.com/18603248/72249498-825b3180-35c7-11ea-924d-7933f818100b.png">

**Comment by Kneesnap** [comment]
It sounds to me like Lombok was not properly installed.
