### ISSUE TITLE
Export models with animations

### ISSUE THREAD

**Issue by acyc070** [Kneesnap/FrogLord#31]
add a button to export the models with BYTE translation type in .obj format(1 model for 1 frame). for QUAT .dae, .glb, .fbx
textures in .png

**Comment by Kneesnap** [comment]
Unfortunately, .dae and .fbx files are not supported. I'd like to support them, but they are very hefty file formats, with very few options for supporting them properly. Is there a reason you cannot export to .obj then convert to .dae, .glb, or .fbx using another tool?

**Comment by acyc070** [comment]
ok, fbx and dae has bad support, but obj DON'T support rigging, skeletal animations (convert QUAT animations to skeletal) https://www.reddit.com/r/Maya/comments/8dcl2s/export_animation_and_skeleton_with_obj_export/

**Comment by Kneesnap** [comment]
.mm3d export was the best option I found for exporting rigged models. It's
not ideal for compatibility, but I've yet to find something reasonable to
support which can do rigging. glb might be feasible though. Don't know yet,
I'll need to look into it.

**Comment by acyc070** [comment]
are you working on implementing this?

**Comment by acyc070** [comment]
In general, this is the very first version how it should look
![APPROX](https://github.com/Kneesnap/FrogLord/assets/112773735/ec145c41-4287-4071-b6c6-26d4b194672a)

**Comment by Kneesnap** [comment]
Model exporting is not something I'm working on right now, MediEvil II
support is the current focus. I'll try to find some time to look at model
exporting again sometime soon though.

**Comment by acyc070** [comment]
Ok I'll close this issue for a while
